### PR TITLE
edited project create script for python projects

### PR DESCRIPTION
**Pull request by planetplut0**
I have edited projectCreate script so that it supports python projects by creating appropriate files and directories

### CODE REVIEW

**Comment by RishabhRD** [comment]
It's good to go. I thought of implicitly initializing git repository but maybe many times we don't want it. So merging it. :-)

**Comment by planetplut0** [comment]
Nice idea , we can pass option like -g or --git to initialize a git repo in the project folder . Additionally we also pass the project name and programming language in command line options itself. (like: projectCreate -n myproject -l py -g )What do you say ??

**Comment by RishabhRD** [comment]
We can do that! This can be one approach. Making it interactive can be other. Because in projects like gradle, many other parameters need to be there. And hence those need to be interactive. But the options suggested are very generic and we can proceed with it. Can you modify the script maybe in other pull request? (I would take some time if I would implement it because I am working on some another project.) Thanks for the improvement. :smile:

**Comment by planetplut0** [comment]
I would love to do that 😃

**Comment by RishabhRD** [comment]
Thanks... I really appreciate that. Looking forward for pull request :+1:

**Pull request merged**
